platform :ios, '10.0'
use_frameworks!

target 'EGVApp' do

  # Pods for EGVApp
  pod 'Kingfisher'
  pod 'SwiftyJSON'
  pod 'SwiftHash'
  pod 'GoogleMaps'
  pod 'GooglePlaces'
  pod 'SwiftKeychainWrapper'
  pod 'CropViewController'
  pod 'XLPagerTabStrip'
  pod 'XLActionController'
  pod 'XLActionController/Twitter'
  pod 'TagListView'
  pod 'JGProgressHUD'
  pod 'NVActivityIndicatorView'
  pod 'SkyFloatingLabelTextField'
  pod 'NextGrowingTextView'
  pod 'SwiftGifOrigin'
  pod 'ActionSheetPicker-3.0'
  pod 'ENMBadgedBarButtonItem'
  pod 'FontAwesome.swift'
  pod 'Firebase/Core'
  pod 'Firebase/Firestore'
  pod 'Firebase/Auth'
  pod 'Firebase/Storage'
  pod 'Firebase/Messaging'
  pod 'Firebase/Analytics'
  pod 'CodableFirebase'
  pod 'YPImagePicker'
  pod 'FaveButton'
  pod 'KMPlaceholderTextView', '~> 1.4.0'
  pod 'INSPhotoGallery'
  pod 'InstantSearchClient', '~> 7.0'
  pod 'SwiftRichString'
  pod 'STPopup'
  pod 'RichEditorView'
  pod 'Sheeeeeeeeet'
end
